apiVersion: v1
kind: Secret
metadata:
  name: {{ include "squid-indexer.fullname" . }}-secret
  labels:
    {{- include "squid-indexer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.clickhouse.enabled }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.auth.password | b64enc | quote }}
  {{- else }}
  CLICKHOUSE_PASSWORD: {{ .Values.externalClickhouse.password | b64enc | quote }}
  {{- end }} 