# Default values for squid-indexer
replicaCount: 1

image:
  repository: squid-indexer
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: squid-indexer.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application configuration
config:
  # Network Configuration (Required)
  gatewayUrl: "https://v2.archive.subsquid.io/network/ethereum-mainnet"
  rpcEthHttp: "https://rpc.ankr.com/eth"
  rpcEthRateLimit: 10

  # Processing Configuration
  batchSize: 100
  balanceChangesTtlDays: 90

  # Storage Flags
  storeBlocks: false
  storeTransactions: false
  storeLogs: false
  storeTransfers: true
  storeNativeBalances: false
  storeBalanceIncreases: true
  storeBalanceDecreases: true

  # ClickHouse Retry Configuration
  clickhouseTimeout: 30000
  clickhouseMaxRetries: 3
  clickhouseRetryDelay: 1000
  clickhouseMaxRetryDelay: 10000

# ClickHouse configuration
clickhouse:
  enabled: true
  auth:
    username: default
    password: password123
    database: base
  service:
    ports:
      http: 8123
      tcp: 9000
  persistence:
    enabled: true
    size: 20Gi
    storageClass: ""
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# External ClickHouse (when clickhouse.enabled = false)
externalClickhouse:
  host: "clickhouse.default.svc.cluster.local"
  port: 8123
  username: default
  password: password123
  database: base

# Migrations
migrations:
  enabled: true
  image:
    repository: squid-indexer
    tag: "latest"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Health checks
healthcheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Monitoring
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s 